servers = {
  "Frontend" => { :ip => "192.168.56.2", :ssh_port => 2200, :mem => 1024 },
  "Backend" => { :ip => "192.168.56.3", :ssh_port => 2222, :mem => 1024 }
}

Vagrant.configure("2") do |config|
    
    servers.each_with_index do |(hostname, info), index|
      config.vm.define hostname do |cfg|
        cfg.vm.provider :virtualbox do |vb, override|
          config.vm.box = "bento/ubuntu-18.04"
          override.vm.network "private_network", ip: "#{info[:ip]}"
          override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh_port]}", id: "ssh", auto_correct: true
          override.vm.hostname = hostname
          vb.name = hostname
          vb.memory = "#{info[:mem]}"
        end
      end
    end
end